[package]
name = "contract"
version = "0.1.0"
edition = "2018"

[dependencies]
casper-contract = { version = "1.4.3", features = [] }
casper-types = "1.4.5"
sha2 = { version = "0.9", default-features = false }


[[bin]]
name = "contract"
path = "src/main.rs"
bench = false
doctest = false
test = false

[profile.release]
codegen-units = 1
lto = true


# test-support
# [features]
# default = ["casper-contract/test-support"]

